development:
  development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: Yellow_tech_2_production
  username: Yellow_tech_2
  password: <%= ENV["YELLOW_TECH_2_DATABASE_PASSWORD"] %>
